<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RILWcPl' shared service.

return $this->privates['.service_locator.RILWcPl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'seasonRepository' => ['privates', 'App\\Repository\\SeasonRepository', 'getSeasonRepositoryService.php', true],
], [
    'seasonRepository' => 'App\\Repository\\SeasonRepository',
]);
