<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.piwk0mf' shared service.

return $this->privates['.service_locator.piwk0mf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'actor' => ['privates', '.errored..service_locator.piwk0mf.App\\Entity\\Actor', NULL, 'Cannot autowire service ".service_locator.piwk0mf": it references class "App\\Entity\\Actor" but no such service exists.'],
    'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService.php', true],
], [
    'actor' => 'App\\Entity\\Actor',
    'slugify' => 'App\\Service\\Slugify',
]);
