<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tXoa_ER' shared service.

return $this->privates['.service_locator.tXoa_ER'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'program' => ['privates', '.errored..service_locator.tXoa_ER.App\\Entity\\Program', NULL, 'Cannot autowire service ".service_locator.tXoa_ER": it references class "App\\Entity\\Program" but no such service exists.'],
], [
    'program' => 'App\\Entity\\Program',
]);
