<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GUPaZAd' shared service.

return $this->privates['.service_locator.GUPaZAd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\WildController::showEpisode' => ['privates', '.service_locator.PqXbmwR', 'get_ServiceLocator_PqXbmwRService.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\WildController:showEpisode' => ['privates', '.service_locator.PqXbmwR', 'get_ServiceLocator_PqXbmwRService.php', true],
], [
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\WildController::showEpisode' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
    'App\\Controller\\WildController:showEpisode' => '?',
]);
