<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PqXbmwR' shared service.

return $this->privates['.service_locator.PqXbmwR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'episode' => ['privates', '.errored..service_locator.PqXbmwR.App\\Entity\\Episode', NULL, 'Cannot autowire service ".service_locator.PqXbmwR": it references class "App\\Entity\\Episode" but no such service exists.'],
], [
    'episode' => 'App\\Entity\\Episode',
]);
