<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1zNmpZJ' shared service.

return $this->privates['.service_locator.1zNmpZJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'actorRepository' => ['privates', 'App\\Repository\\ActorRepository', 'getActorRepositoryService.php', true],
], [
    'actorRepository' => 'App\\Repository\\ActorRepository',
]);
