<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TlC5_Zq' shared service.

return $this->privates['.service_locator.TlC5_Zq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'episodeRepository' => ['privates', 'App\\Repository\\EpisodeRepository', 'getEpisodeRepositoryService.php', true],
], [
    'episodeRepository' => 'App\\Repository\\EpisodeRepository',
]);
