<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.58Rml10' shared service.

return $this->privates['.service_locator.58Rml10'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'programRepository' => ['privates', 'App\\Repository\\ProgramRepository', 'getProgramRepositoryService.php', true],
], [
    'programRepository' => 'App\\Repository\\ProgramRepository',
]);
