<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.piwk0mf.App\Entity\Actor' shared service.

include_once $this->targetDirs[3].'/src/Entity/Actor.php';

return $this->privates['.errored..service_locator.piwk0mf.App\\Entity\\Actor'] = new \App\Entity\Actor();
