<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ggk.SCy' shared service.

return $this->privates['.service_locator.Ggk.SCy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'program' => ['privates', '.errored..service_locator.Ggk.SCy.App\\Entity\\Program', NULL, 'Cannot autowire service ".service_locator.Ggk.SCy": it references class "App\\Entity\\Program" but no such service exists.'],
    'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService.php', true],
], [
    'program' => 'App\\Entity\\Program',
    'slugify' => 'App\\Service\\Slugify',
]);
