<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.K0SvH3w' shared service.

return $this->privates['.service_locator.K0SvH3w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'actor' => ['privates', '.errored..service_locator.K0SvH3w.App\\Entity\\Actor', NULL, 'Cannot autowire service ".service_locator.K0SvH3w": it references class "App\\Entity\\Actor" but no such service exists.'],
], [
    'actor' => 'App\\Entity\\Actor',
]);
