<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZRBM5C\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZRBM5C/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGZRBM5C.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGZRBM5C\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGZRBM5C\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GZRBM5C',
    'container.build_id' => 'a77617fe',
    'container.build_time' => 1575277833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZRBM5C');
